name: Tennis-Player-Match-Manage-System

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: ['8.0']
        
    # services:
    #   mongo:
    #     image: mongo:latest
    #     ports:
    #       - 27017:27017
        # options: >-
        #   --health-cmd "mongo --eval 'db.runCommand(\"ping\").ok'"
        #   --health-interval 10s
        #   --health-timeout 5s
        #   --health-retries 10
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-username: supercharge
          mongodb-password: secret
          mongodb-db: supercharge

      - name: Install dependencies
        run: npm install

      # - name: Wait for MongoDB to be ready
      #   run: |
      #     echo "Waiting for MongoDB to be ready..."
      #     for i in {1..30}; do
      #       mongo --eval "db.runCommand('ping').ok" && echo "MongoDB is ready" && exit 0
      #       echo "Waiting for MongoDB... ($i/30)"
      #       sleep 5
      #     done
      #     echo "MongoDB did not become ready in time" && exit 1

      - name: Run tests
        run: npm test

      - name: Start server
        run: node ./serverREST.js

      - name: Wait for server to start
        run: sleep 10

      - name: Verify deployment
        run: curl --fail http://localhost:3000/players.html

      - name: Deploy to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
